apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wine-cellar
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: wine-cellar
spec:
  source:
    git:
      url: https://github.com/SteveDZ/wine-cellar.git
      ref:
        branch: main
